//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int MedicineID { get; set; }
        public int WorkerID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public int Amount { get; set; }
        public decimal Price { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
